# Generated by Django 4.0.5 on 2022-07-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'ordering': ['-fecha_publicacion']},
        ),
    ]
