# Generated by Django 4.0.5 on 2022-07-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0002_remove_juegos_usuario_remove_musica_usuario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Juegos',
            new_name='Juego',
        ),
        migrations.RenameModel(
            old_name='Series',
            new_name='Serie',
        ),
    ]
