# Generated by Django 4.0.5 on 2022-07-21 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0003_rename_juegos_juego_rename_series_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='juegos'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='musica'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='peliculas'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='series'),
        ),
    ]
