# Generated by Django 4.0.5 on 2022-07-22 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0004_alter_juego_imagen_alter_musica_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='subtitulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
