# Generated by Django 4.0.5 on 2022-07-22 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0005_pelicula_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
