# Generated by Django 4.0.5 on 2022-07-22 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0006_alter_pelicula_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
