# Generated by Django 4.0.5 on 2022-07-23 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clapperboardApp', '0008_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='imagen',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='autor',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.CharField(max_length=800),
        ),
    ]
