# Generated by Django 4.0.5 on 2022-07-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clapperboardApp', '0008_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
